function RTW_SidParentMap() {
    this.sidParentMap = new Array();
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1086"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1087"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1588"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1392"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1394"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1398"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1399"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1089"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1090"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1091"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1092"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1396"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1397"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1094"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1095"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1097"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1096"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1098"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1099"] = "test_HelicopterModelingSimulation_disc_copy:1085";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1392:1"] = "test_HelicopterModelingSimulation_disc_copy:1392";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1392:17"] = "test_HelicopterModelingSimulation_disc_copy:1392";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1392:16"] = "test_HelicopterModelingSimulation_disc_copy:1392";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1392:3"] = "test_HelicopterModelingSimulation_disc_copy:1392";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1090:36"] = "test_HelicopterModelingSimulation_disc_copy:1090";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1090:37"] = "test_HelicopterModelingSimulation_disc_copy:1090";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1090:38"] = "test_HelicopterModelingSimulation_disc_copy:1090";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1090:39"] = "test_HelicopterModelingSimulation_disc_copy:1090";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1090:40"] = "test_HelicopterModelingSimulation_disc_copy:1090";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1090:41"] = "test_HelicopterModelingSimulation_disc_copy:1090";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1090:42"] = "test_HelicopterModelingSimulation_disc_copy:1090";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1090:43"] = "test_HelicopterModelingSimulation_disc_copy:1090";
    this.sidParentMap["test_HelicopterModelingSimulation_disc_copy:1090:44"] = "test_HelicopterModelingSimulation_disc_copy:1090";
    this.getParentSid = function(sid) { return this.sidParentMap[sid];}
}
    RTW_SidParentMap.instance = new RTW_SidParentMap();
